branch-defaults:
  default:
    environment: taiyuan-eb-api
    group_suffix: null
global:
  application_name: taiyuan-eb-api
  branch: null
  default_ec2_keyname: taiyuan
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
